---

- name: add schema to Tenant
  hosts: mso
  connection: local
  gather_facts: false

  vars_files:
    - external_vars.yml

  vars_prompt:                   #  will prompt for password
     - name: uname
       prompt: username
       private: no               # private: yes means that username will be masked in screen when you type it in

     - name: pass
       prompt: password
       private: yes              # private: no means that password (OTP token value) will not be echoed when you type it in 


  tasks:
    - name: copy from kvalue1 to kvalue
      template:
        src: kvalue1
        dest: kvalue
    
    - name: Add a new schema
      cisco.mso.mso_schema_template:
        host: "{{ host }}"
        username: "{{ uname }}"    # will read from vars_prompt and will prompt for username
        password: "{{ pass }}"     # will read from vars_prompt and will prompt for password
        tenant: "{{ tenant }}"
        schema: "{{ schema }}"
        template: "{{ template }}"
        login_domain: "{{ login_domain }}"
        validate_certs: "no"
        use_proxy: false
        state: present
      delegate_to: localhost

    - name: Asspcoate schema with site
      cisco.mso.mso_schema_site:
        host: "{{ host }}"
        username: "{{ uname }}"
        password: "{{ pass }}"
        schema: "{{ schema }}"
        site: "{{ site1 }}"
        login_domain: "{{ login_domain }}"
        validate_certs: "no"
        use_proxy: false
        template: "{{ template }}"
        state: present
      delegate_to: localhost

    - name: Asspcoate schema with site
      cisco.mso.mso_schema_site:
        host: "{{ host }}"
        username: "{{ uname }}"
        password: "{{ pass }}"
        schema: "{{ schema }}"
        site: "{{ site2 }}"
        login_domain: "{{ login_domain }}"
        validate_certs: "no"
        use_proxy: false
        template: "{{ template }}"
        state: present
      delegate_to: localhost



# usage:  ansible-playbook 1b.AddSchema.yaml -i hosts -vvv
# Note, that since this is for OTP, you can't prepopulate password from vault.  You have to put in your OTP Token value when password is prompted for
# mso_schema – Manage schemas:  https://docs.ansible.com/ansible/latest/modules/mso_schema_module.html#mso-schema-module
# mso_schema_site – Manage sites in schemas: https://docs.ansible.com/ansible/latest/modules/mso_schema_site_module.html#mso-schema-site-module
